"""
core/models.py

Canonical schema contracts for the systematic research data platform.
These are the source of truth for all dataset definitions, ingestion records,
and health reports. Both Rust and Python layers must conform to these contracts.
"""

import hashlib
import json
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class ColumnType(str, Enum):
    INT = "int"
    FLOAT = "float"
    STRING = "string"
    DATE = "date"
    TIMESTAMP = "timestamp"
    BOOLEAN = "boolean"


class DatasetFrequency(str, Enum):
    INTRADAY = "intraday"
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    ON_DEMAND = "on_demand"


class HealthStatus(str, Enum):
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    FAILING = "failing"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Schema contracts
# ---------------------------------------------------------------------------


class ColumnSchema(BaseModel):
    """Definition of a single column in a canonical dataset."""

    name: str
    dtype: ColumnType
    nullable: bool = False
    description: str = ""


class DatasetSchema(BaseModel):
    """
    Canonical schema for a dataset.

    The schema hash is derived deterministically from column names, types,
    and nullability — not from descriptions or metadata. This ensures hash
    stability across documentation changes.
    """

    name: str
    version: str
    columns: list[ColumnSchema]

    def compute_hash(self) -> str:
        """
        Deterministic SHA-256 hash of the schema contract.
        Columns are sorted by name to ensure order-independence.
        """
        fingerprint = {
            "name": self.name,
            "version": self.version,
            "columns": [
                {
                    "name": col.name,
                    "dtype": col.dtype.value,
                    "nullable": col.nullable,
                }
                for col in sorted(self.columns, key=lambda c: c.name)
            ],
        }
        return hashlib.sha256(
            json.dumps(fingerprint, sort_keys=True).encode()
        ).hexdigest()


# ---------------------------------------------------------------------------
# Registry models
# ---------------------------------------------------------------------------


class DatasetRegistration(BaseModel):
    """
    Registration record for a dataset in the metadata registry.
    Created once per dataset; updated on schema version bump.
    """

    name: str
    version: str
    owner: str
    expected_frequency: DatasetFrequency
    schema_hash: str
    description: str = ""


class IngestionRecord(BaseModel):
    """
    Immutable record of a single ingestion run.
    Written after a successful ingest; never updated.
    """

    run_id: str  # UUID, generated by the pipeline
    dataset_name: str
    version: str
    ingested_at: datetime
    row_count: int
    checksum: str  # SHA-256 of the output Parquet file
    source_path: str
    partition_path: str
    schema_hash: str


# ---------------------------------------------------------------------------
# Health models
# ---------------------------------------------------------------------------


class HealthReport(BaseModel):
    """
    Result of a health check run against a dataset.
    Each check is an explicit boolean — no implicit aggregation.
    """

    dataset_name: str
    checked_at: datetime
    status: HealthStatus
    freshness_ok: bool
    volume_ok: bool
    null_ratio_ok: bool
    schema_hash_ok: bool
    details: dict[str, Any] = Field(default_factory=dict)
